### ISSUE TITLE
Inconsistensies between LO and command line: no space after punctuation

### ISSUE THREAD

**Issue by snomos** [divvun/libreoffice-divvun#3]
The following command gives no indication of trouble:

```
$ printf '– Mu bárdni áigu šaddat doavttirin.\n– Lea go son álgán doavttirskuvlii?\n' | tools/grammarcheckers/modes/trace-smegram1-blanktag.mode 
[...]
: 
"<doavttirin>"
	"doavttir" N Sem/Hum Ess <W:0.0>
"<.>"
	"." CLB <W:0.0>
:\n
"<–>"
	"–" PUNCT <W:0.0> <firstWordOfParagraph>
: 
[...]
```

But still, when the same files are used in LO, there are tiny blue underlines under the final full stop of a sentence:

<img width="908" alt="image" src="https://user-images.githubusercontent.com/1255285/51532900-0c0b6f80-1e4a-11e9-9d33-d1a52e8b13ba.png">

Because of this inconstancy I am not able to fix it - there is nothing to fix in the data I have access to.

**Comment by unhammer** [comment]
There's probably no newline after the dot in the data sent by LibreOffice to divvun. 

If I recall correctly, LO sends one "paragraph" (as LO defines paragraphs) at a time to grammar checkers. 
It's easy enough to reproduce on the command line:

```
$ printf '.' | modes/smegram.mode
"<.>"
        "." CLB <W:0.0> <NoSpaceAfterPunctMark> &no-space-after-punct-mark
no-space-after-punct-mark

```

A simple fix would be to have the CG rule check that there's at least one cohort to the right. Use the `>`  [span window boundaries](http://beta.visl.sdu.dk/cg3/single/#test-spanning) modifier on the context condition since `.` is `DELIMITER` in the grammar.

**Comment by snomos** [comment]
Worked like a charm! Thanks 👍
